services:
  postgres:
    image: postgres:15
    ports:
      - target: 5432
        published: 15432
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test

  neo4j:
    image: neo4j:5.6
    healthcheck:
      test: neo4j status || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      # http
      - target: 7474
        published: 17474
      # bolt
      - target: 7687
        published: 17687

  syncer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      POSTGRES_URL: "postgres://user:pass@postgres:5432/test"
      NEO4J_BOLT_URL: "bolt://neo4j:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "password"
