name: Docker

on:
  push:
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "deno.jsonc"
      - "deno.lock"
      - "*.ts"

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' && github.ref_name == "main" }}
          tags: ghcr.io/${{ github.repository_owner }}/neo4j-syncer:latest
